services:
  server:
    build: backend/.
    container_name: server
    env_file:
      - backend/.env.docker
    ports:
      - 4000:4000
    image: 'server'
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pw
    ports:
      - 27017:27017
    volumes: [mongodata:/data/db]

  api-tester:
    build: backend/tests/.
    container_name: api-test
    ports:
      - 7001:7001
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - server
    image: 'api-tester'

  client-dev:
    build: frontend/.
    container_name: client-dev
    env_file:
      - frontend/.env.development
    ports:
      - 3000:3000
    depends_on:
      - server
    image: 'client-dev'

volumes:
  mongodata:
    driver: local
