services:
  server:
    build: backend/.
    container_name: server
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    image: 'server:v1'

  api-tester:
    build: backend/tests/.
    container_name: api-test
    ports:
      - 7001:7001
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - server
    image: 'api-tester:v1'
