services:
  server:
    build: backend/.
    container_name: server
    env_file:
      - backend/.env
    ports:
      - 4000:4000
    image: 'server'

  api-tester:
    build: backend/tests/.
    container_name: api-test
    ports:
      - 7001:7001
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - server
    image: 'api-tester'

  client-dev:
    build: frontend/.
    container_name: client-dev
    ports:
      - 3000:3000
    depends_on:
      - server
    image: 'client-dev'
